version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(funcName)s:%(lineno)d - %(levelname)s - %(message)s"
  color:
    () : logger.formatters.ColorFormatter
    format: "%(asctime)s - %(name)s - %(funcName)s:%(lineno)d - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: color
    stream: ext://sys.stdout

loggers:
  myapp:
    level: INFO
    handlers: [console]
    propagate: False

root:
  level: WARNING
  handlers: [console]