# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x03\x64\x61i\"Y\n\rSensorReading\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x13\n\x0bsensor_type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"4\n\rSensorRequest\x12#\n\x07reading\x18\x01 \x01(\x0b\x32\x12.dai.SensorReading\"2\n\x0eSensorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x84\x01\n\rSensorService\x12\x36\n\x0bSendReading\x12\x12.dai.SensorRequest\x1a\x13.dai.SensorResponse\x12;\n\x0eStreamReadings\x12\x12.dai.SensorRequest\x1a\x13.dai.SensorResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORREADING']._serialized_start=21
  _globals['_SENSORREADING']._serialized_end=110
  _globals['_SENSORREQUEST']._serialized_start=112
  _globals['_SENSORREQUEST']._serialized_end=164
  _globals['_SENSORRESPONSE']._serialized_start=166
  _globals['_SENSORRESPONSE']._serialized_end=216
  _globals['_SENSORSERVICE']._serialized_start=219
  _globals['_SENSORSERVICE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
