# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import sensor_pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sensor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensorServiceStub(object):
    """Servizio gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendReading = channel.unary_unary(
                '/dai.SensorService/SendReading',
                request_serializer=sensor_pb2.SensorRequest.SerializeToString,
                response_deserializer=sensor_pb2.SensorResponse.FromString,
                _registered_method=True)
        self.StreamReadings = channel.stream_unary(
                '/dai.SensorService/StreamReadings',
                request_serializer=sensor_pb2.SensorRequest.SerializeToString,
                response_deserializer=sensor_pb2.SensorResponse.FromString,
                _registered_method=True)


class SensorServiceServicer(object):
    """Servizio gRPC
    """

    def SendReading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamReadings(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendReading': grpc.unary_unary_rpc_method_handler(
                    servicer.SendReading,
                    request_deserializer=sensor_pb2.SensorRequest.FromString,
                    response_serializer=sensor_pb2.SensorResponse.SerializeToString,
            ),
            'StreamReadings': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamReadings,
                    request_deserializer=sensor_pb2.SensorRequest.FromString,
                    response_serializer=sensor_pb2.SensorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dai.SensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dai.SensorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SensorService(object):
    """Servizio gRPC
    """

    @staticmethod
    def SendReading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dai.SensorService/SendReading',
            sensor_pb2.SensorRequest.SerializeToString,
            sensor_pb2.SensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamReadings(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/dai.SensorService/StreamReadings',
            sensor_pb2.SensorRequest.SerializeToString,
            sensor_pb2.SensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
